# Используем официальный образ PHP с Apache
FROM php:8.2-apache

# Устанавливаем необходимые зависимости
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Включаем модуль Apache rewrite
RUN a2enmod rewrite

# Копируем исходный код приложения в контейнер
COPY . /var/www/html/

# Устанавливаем рабочую директорию
WORKDIR /var/www/html

# Устанавливаем права на запись для Apache
RUN chown -R www-data:www-data /var/www/html

# Открываем порт 80
EXPOSE 80