services:
  web-zoo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
  
  db:
    restart: on-failure
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - "8080:80"
    environment:
     PMA_HOST: db
     MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data: